### ISSUE TITLE
failed to install on Almalinux 8

### ISSUE THREAD

**Issue by szelga** [linuxhq/ansible-role-elrepo#8]
[v0.0.6](https://github.com/linuxhq/ansible-role-elrepo/tree/v0.0.6), tested on Almalinux 8.6.
the error is following:

```
TASK [linuxhq.elrepo : Ensure that the elrepo-release package is installed] **********************************************************************************************
fatal: [test-host]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for elrepo-release-8.0-2.el8.elrepo.noarch"}
```

after the

```
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
```

command the installation proceeds as normal.

**Comment by tkimball83** [comment]
Can you test this branch at your earliest convenience?  It includes the order of operations fix and a much needed facelift.

https://github.com/linuxhq/ansible-role-elrepo/tree/gpg_key_fix_facelift

**Comment by szelga** [comment]
worked like charm on a fresh Almalinux 8.4 install.

**Comment by tkimball83** [comment]
Branch has been merged and tagged with v0.0.7.  Thanks for the assistance!

**Comment by szelga** [comment]
could you please also check the status of this new version in ansible galaxy? installation fails with an error, that it can't find the `v0.0.7` version.

**Comment by tkimball83** [comment]
I’ll have to look into why that didn’t import automatically.  Anyhow, manual import completed, and I see v0.0.7 in the version list.

**Comment by szelga** [comment]
thanks.
